CREATE TABLE users (
                       id UUID PRIMARY KEY,
                       name TEXT NOT NULL,
                       email TEXT UNIQUE NOT NULL,
                       phone TEXT NOT NULL,
                       role TEXT NOT NULL,
                       is_active BOOL NOT NULL DEFAULT TRUE
);

CREATE TABLE address (
                         customer_id UUID PRIMARY KEY NOT NULL REFERENCES users(id) ON DELETE CASCADE,
                         street TEXT NOT NULL,
                         apartment TEXT NOT NULL,
                         city TEXT NOT NULL
);

CREATE TABLE products (
                          id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                          name TEXT NOT NULL,
                          price NUMERIC(12,2) NOT NULL CHECK (price >= 0),
                          cost NUMERIC(12,2) NOT NULL CHECK (cost >= 0),
                          stock INT NOT NULL CHECK (stock >= 0),
                          stock_threshold INT NOT NULL DEFAULT 1000 CHECK (stock_threshold >= 0),
                          image_url TEXT,
                          is_active BOOL NOT NULL DEFAULT TRUE
);

CREATE TABLE orders (
                        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        customer_id UUID NOT NULL REFERENCES users(id),
                        employee_id UUID REFERENCES users(id),
                        status TEXT NOT NULL DEFAULT 'PENDING',
                        total_amount NUMERIC(12,2) NOT NULL CHECK (total_amount >= 0),
                        total_cost NUMERIC(12,2) NOT NULL CHECK (total_cost >= 0),
                        created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                        updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                        is_active BOOL NOT NULL DEFAULT TRUE
);

CREATE TABLE order_items (
                             id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                             order_id BIGINT NOT NULL REFERENCES orders(id) ON DELETE CASCADE,
                             product_id BIGINT NOT NULL REFERENCES products(id),
                             quantity INT NOT NULL CHECK (quantity >= 1),
                             price NUMERIC(12,2) NOT NULL CHECK (price >= 0),
                             cost NUMERIC(12,2) NOT NULL CHECK (cost >= 0),
                             is_active BOOL NOT NULL DEFAULT TRUE
);